### ISSUE TITLE
[BUG] Viewers that include xbrlviewer.js as part of the output don't link to the included version 

### ISSUE THREAD

**Issue by sagesmith-wf** [Arelle/ixbrl-viewer#413]
### What happened?

Zipped output versions of the ixbrl-viewer include a copy of the [`ixbrlviewer.js`](https://github.com/Workiva/ixbrl-viewer/blob/41250b59ab2c7723a9aa61b09cc8539ae0de298f/iXBRLViewerPlugin/iXBRLViewer.py#L436) but don't actually link to it

### Version

1.1.61+  (latest master locally)

### With which browsers are you experiencing the bug?

Firefox, Chrome, Safari, Microsoft Edge

### Documents

[ixds.zip](https://github.com/Workiva/ixbrl-viewer/files/11384679/ixds.zip)

### Screenshots

<img width="322" alt="Screenshot 2023-05-03 at 10 13 54 AM" src="https://user-images.githubusercontent.com/17255946/235976419-e23242f4-8610-4438-b46a-b7df225bc4f6.png">
<img width="912" alt="Screenshot 2023-05-03 at 10 14 40 AM" src="https://user-images.githubusercontent.com/17255946/235976606-e1711e24-f89c-42b5-b949-fe291b473b8b.png">

**Comment by paulwarren-wk** [comment]
How are you producing the zipped output version?  It looks like `scriptUrl` is not being set correctly when the viewer is created, but I'm not sure where it's being called from.

**Comment by austinmatherne-wk** [comment]
Resolved by #516
