### ISSUE TITLE
[REQUEST] - Add a "viewer" url parameter 

### ISSUE THREAD

**Issue by lukepint-wk** [Arelle/ixbrl-viewer#571]
### What should we change and why?

Add a new "viewer" url parameter to determine if the Inline Viewer experience should execute on page load.

This would allow hosting a single copy of the report with an easy way of disabling the viewer.

**Comment by paulwarren-wk** [comment]
This would be straightforward to add, although I'd note that if you're using stub viewer mode, you can already load the non-viewer document directly.

I think this option probably only makes sense for non-stub-viewer mode anyway.

**Comment by paulwarren-wk** [comment]
As an example of how stub viewer mode could help here, when using stub viewer mode, the viewer entry point is `ixbrlviewer.html`, e.g.:

https://filings.xbrl.org/213800DAZ89VABJPBD93/2023-06-30/ESEF/DK/0/213800DAZ89VABJPBD93-2023-06-30-da/reports/ixbrlviewer.html

This loads the original (almost) unmodified filing from here:

https://filings.xbrl.org/213800DAZ89VABJPBD93/2023-06-30/ESEF/DK/0/213800DAZ89VABJPBD93-2023-06-30-da/reports/213800DAZ89VABJPBD93-2023-06-30-da.xhtml

So you can get the non-viewer version just by switching the URL.

**Comment by lukepint-wk** [comment]
Closed with the addition of `?disable-viewer` in #579
