### ISSUE TITLE
[BUG]Fact properties are not getting loaded in the latest version 

### ISSUE THREAD

**Issue by GauthamDT** [Arelle/ixbrl-viewer#634]
### What happened?

Fact properties are not getting loaded in the latest version 

### Version

Latest

### With which browsers are you experiencing the bug?

Chrome

### Documents

[213800ORZ521W585SY02-2024-02-29-en.zip](https://github.com/Arelle/ixbrl-viewer/files/14360657/213800ORZ521W585SY02-2024-02-29-en.zip)

**Comment by paulwarren-wk** [comment]
Can you explain exactly what happens and provide a screenshot?  Is there anything on the dev console?

I've just tried the above document here, and it seems to load fine.

**Comment by GauthamDT** [comment]
The issue is in common viewer

**Comment by GauthamDT** [comment]
this is fixed in the latest version
