### ISSUE TITLE
[BUG] Inline Rendering Issue - Incorrect period shown

### ISSUE THREAD

**Issue by GauthamDT** [Arelle/ixbrl-viewer#649]
### What happened?

We are facing the issue on latest version 2.23.15 Arelle software that the inline viewer showing incorrect period instead of assigned correct period.

The issue happen while choose the option “Open File Inline Doc Set” in that while uploading the dual instant file.

### Version

2.23.15

### With which browsers are you experiencing the bug?

Chrome

### Documents

[tmp-20231231_iXBRL.zip](https://github.com/Arelle/ixbrl-viewer/files/14719656/tmp-20231231_iXBRL.zip)

### Screenshots

![ss](https://github.com/Arelle/ixbrl-viewer/assets/29231044/a147772d-9740-4776-94d8-18cfa3f3ebf2)

**Comment by paulwarren-wk** [comment]
That screenshot is not of the Arelle iXBRL viewer.  That's the SEC iXBRL viewer.

**Comment by GauthamDT** [comment]
Please find the screenshot taken from Arelle ixbrl viewer
![image](https://github.com/Arelle/ixbrl-viewer/assets/29231044/d7a3d27a-4a85-473c-9053-9becd6761c29)

**Comment by paulwarren-wk** [comment]
That's the SEC viewer that forms part of the EdgarRenderer plugin https://github.com/Arelle/EdgarRenderer/tree/master/ixviewer-src

**Comment by GauthamDT** [comment]
Alright will raise with them ...thanks
