### ISSUE TITLE
[BUG] iXBRLViewerPlugin: Build iXBRL with EFRAG Sample XBRL file thanks to iXBRLViewerPlugin plugin fails

### ISSUE THREAD

**Issue by frinux** [Arelle/ixbrl-viewer#655]
### What happened?

I am trying to produce an iXBRL file from a sample xhtml file produced by EFRAG:
- zip file containing XBRL files is [here](https://xbrl.efrag.org/downloads/Annex-2-Draft-ESRS-Set1-illustrative-examples-of-XBRL-reports.zip) 
- this zip is published [here](https://www.efrag.org/Lab4)
- an example file is provided in the documents field

I am following the steps given in the README:
- plugin is installed in Arelle GUI
- XHTML file is opened in GUI
- menu tools -> iXBRL viewer -> Save Viewer

Result: 
- exception in the logs
- no file generated

Thanks in advance!

### Version

1.4.22

### With which browsers are you experiencing the bug?

Firefox, Chrome, Safari, Microsoft Edge

### Documents

[efrag-2026-12-31-en.zip](https://github.com/Arelle/ixbrl-viewer/files/14933075/efrag-2026-12-31-en.zip)

### Screenshots

![image](https://github.com/Arelle/ixbrl-viewer/assets/636404/af0d52ec-68bb-4c39-a4f2-fe971ea5b286)

![image](https://github.com/Arelle/ixbrl-viewer/assets/636404/a498c3ff-51cb-450c-b6c1-95cda03c3516)

**Comment by austinmatherne-wk** [comment]
Hi @frinux,

I'm unable to replicate this issue with the latest version of Arelle and ixbrl-viewer. Can you check what version of Arelle you're using?

**Comment by frinux** [comment]
Sure! 
I'm on Arelle 2.25.8 on Ubuntu (downloaded the tgz this afternoon from the website)

![image](https://github.com/Arelle/ixbrl-viewer/assets/636404/4e5d3dbd-abb0-439a-9c1a-57d71a3bd685)
