### ISSUE TITLE
Assets Not Copied to Temporary Directory in GUI Code Path

### ISSUE THREAD

**Issue by austinmatherne-wk** [Arelle/ixbrl-viewer#683]
### What happened?

When opening a report containing relative assets (such as images) via the GUI code path, the assets are not copied to the temporary directory where the viewer is created. As a result, requests for these assets return 404 errors when the viewer is opened.

### Version

1.4.27

### With which browsers are you experiencing the bug?

Firefox, Chrome, Safari, Microsoft Edge

### Documents

[XBRL.zip](https://github.com/Arelle/ixbrl-viewer/files/15474481/XBRL.zip)

**Comment by paulwarren-wk** [comment]
How should this work?  Discovering all such dependencies is non-trivial, as it requires scanning both the HTML and the CSS for relative links.  What do we do about relative URLs that reference an ancestor directory?  

For reports opened via a report package, we could potentially copy the contents of the whole package across.

**Comment by austinmatherne-wk** [comment]
We had a team chat about this and decided to only target report packages for now. If we need to support extracted reports, we'll likely need to perform some trickery from the web server to redirect requests to the original location
