### ISSUE TITLE
[QUESTION] How can i intergrate with my angular project?

### ISSUE THREAD

**Issue by MShahzadulHassan** [Arelle/ixbrl-viewer#693]
### What question do you have? Be sure to check the wiki to see if it has been answered before

Hello, I am integrating the ixbrl-viewer in my angular project to view xhtml files, but it is not working, i installed the ixbrl-viewer using "NPM INSTALL" and also i add it in index.html file like this "<script type="application/javascript" src="https://cdn.jsdelivr.net/npm/ixbrl-viewer@1.4.28/iXBRLViewerPlugin/viewer/dist/ixbrlviewer.js"></script>" and in the component.ts file i declare "declare let ixbrlviewer: any;" but it is not liading ixbrl-viewer. Can you please help me in this how can i load my file in this ixbrl-viewer?
![image](https://github.com/Arelle/ixbrl-viewer/assets/112062622/39bd3303-817d-4d7d-8d02-e1139cefe8a1)
You can also see the error in the screenshot
Thanks in advance!

**Comment by paulwarren-wk** [comment]
As noted [here](https://github.com/Arelle/ixbrl-viewer?tab=readme-ov-file#arelle-ixbrl-viewer)  :

> In order to view an iXBRL report in the viewer, it must first be prepared using the Arelle plugin. The preparation process updates the iXBRL file to include:
> 
> * A link to the JavaScript viewer
> * A block of JSON data that contains the results of processing the XBRL data and associated taxonomy

You will need to follow the instructions for preparing the viewer data using either the [Arelle GUI](https://github.com/Arelle/ixbrl-viewer?tab=readme-ov-file#producing-an-ixbrl-viewer-via-the-arelle-gui) or the [command line](https://github.com/Arelle/ixbrl-viewer?tab=readme-ov-file#producing-an-ixbrl-viewer-via-the-arelle-gui)

**Comment by MShahzadulHassan** [comment]
Thank you
