### ISSUE TITLE
Validation for SBSEF US SEC taxonomy compatibility incorporation[QUESTION] 

### ISSUE THREAD

**Issue by GauthamDT** [Arelle/ixbrl-viewer#698]
### What question do you have? Be sure to check the wiki to see if it has been answered before

Hello Team,

Could you please check and let me know when the validation compatibility for US SBSEF taxonomy will be included inside the arelle.?

**Comment by paulwarren-wk** [comment]
I think this is a question for the main Arelle project, not the iXBRL Viewer - https://github.com/Arelle/Arelle/issues

**Comment by GauthamDT** [comment]
Thanks will raise in Main arelle
