### ISSUE TITLE
[QUESTION] no such option: --save-viewer, failing on Heroku app.

### ISSUE THREAD

**Issue by lucakato** [Arelle/ixbrl-viewer#743]
Hi,
I'm working on [this project](https://github.com/closup/process-xbrl) that uses ixbrl-viewer.

On Heroku, when I deploy it and try to use the viewer, the following error msg appears even though it doesn't show up when I test on local host:
For reference, I am using **`arelle-release`** and **1.4.36 for iXBRLViewerPlugin** but I just updated the plugin version in my .py (didn't clone latest), but it was giving me same issue even before I **changed it from 1.4.8 to 1.4.36**

`f1e59d69de12/output/viewer.html
2024-10-07T23:22:13.726779+00:00 app[web.1]: Validating XBRL...
2024-10-07T23:22:14.081535+00:00 app[web.1]: Usage: main.py [options]
2024-10-07T23:22:14.081545+00:00 app[web.1]: 
2024-10-07T23:22:14.081547+00:00 app[web.1]: main.py: error: no such option: --save-viewer`

the code that causes the error is below:
```Python
    # command to run Arelle process
    plugins = os.path.join(ROOT, "dependencies", "ixbrl-viewer", "iXBRLViewerPlugin")
    viewer_url = "https://cdn.jsdelivr.net/npm/ixbrl-viewer@1.4.36/iXBRLViewerPlugin/viewer/dist/ixbrlviewer.js"

    print('viewer path', viewer_filepath)
    args = f"--plugins={plugins} -f {output_file} --save-viewer {viewer_filepath} --viewer-url {viewer_url}"
    
    args = shlex.split(args)
    setApplicationLocale()
    gettext.install("arelle")
    print("Validating XBRL...")
    parseAndRun(args)
```

below is my requirements.txt as well... which might be causing issues.
```
# This file may be used to create an environment using:
# $ conda create --name <env> --file <this file>
# platform: osx-arm64

#python>=3.11.7
#python==3.12
Flask==3.0.3
jinja2==3.1.2
openpyxl==3.1.2
# pandas==2.0.3
pandas
pip==23.2.1
python-dateutil==2.8.2
setuptools==68.0.0
mammoth == 1.7.0
Flask-Session
bs4
werkzeug
python-dotenv
# io
lxml
uuid
blinker
python-docx

#Additional Arelle requirements
regex
isodate
pyparsing
certifi
pycountry

Pillow==10.4.0
arelle-release
```

**Comment by austinmatherne-wk** [comment]
Hi Luca,

That error indicates that Arelle wasn't able to find and load the ixbrl-viewer plugin. Plugins are searched for relative to the [plugins directory in Arelle](https://github.com/Arelle/Arelle/tree/master/arelle/plugin), so you would need to specify something along the lines of `../../../dependencies/ixbrl-viewer/iXBRLViewerPlugin`. The other option is to [pip install the viewer](https://pypi.org/project/ixbrl-viewer/) which Arelle can discover automatically based on just the name (`ixbrl-viewer`), no paths required.

**Comment by lucakato** [comment]
thanks so much! the second option was super easy, worked. @austinmatherne-wk
