### ISSUE TITLE
[QUESTION] Highlighting of enumeration concepts only works on span elements

### ISSUE THREAD

**Issue by sachakaelin** [Arelle/ixbrl-viewer#761]
### What question do you have? Be sure to check the wiki to see if it has been answered before

Hi all,

it seems the blue border which indicates a selected, tagged value (text) 
![grafik](https://github.com/user-attachments/assets/e226c59e-5f4b-4c90-8f39-fabe60f8d35e)

only shows up for enums, when the class is applied to content which is contained in a span element.
If this is not the case, the highlighting is working, but the border for the selection is not shown:

![grafik](https://github.com/user-attachments/assets/9237c84f-17b5-424e-8104-95509ae72361)

Looking at the CSS of the viewer I guess it's only applying this to span, div, th and td elements but we could not find any spec which prohibits the use of an enum on other HTML elements. In fact the EFRAG Explanatory Note for ESRS show exactly this use case in IAI 10:

![grafik](https://github.com/user-attachments/assets/a5009ad1-4051-414a-b68d-2c4ab2b742e3)

Thanks and kind regards,
Sacha

**Comment by sachakaelin** [comment]
[Examples.zip](https://github.com/user-attachments/files/17802075/Examples.zip)

**Comment by paulwarren-wk** [comment]
This is a bug. For "normal" tags, we either insert a `<span>` or `<div>` or use the nearest `<td>`. For hidden linked facts, we just use the existing HTML element, but as you say, the CSS is restricted to `div`, `span` and `td`/`th`. I'm not sure if we should fix this by de-restricting the CSS, or by inserting wrapper nodes.
