### ISSUE TITLE
[REQUEST] Add closing tag for datatype in search results

### ISSUE THREAD

**Issue by geoffreyPiraprez** [Arelle/ixbrl-viewer#786]
### What should we change and why?

When the viewer is an html file, javascript automatically adds the closing tag when it is missing.
However, when the viewer is an .xhtml file, it gives an error when parsing HTML.

This problem is currently occurring with the recent addition of the datatype in search results.

![image](https://github.com/user-attachments/assets/a9acb735-cb4a-4445-9b80-fe3125ac440c)

https://github.com/Arelle/ixbrl-viewer/blob/a9d7ade16e7d3eed12226bea8eeace90326809b2/iXBRLViewerPlugin/viewer/src/js/inspector.js#L506

I suggest you change the line above to add the closing tag like this:

`$('<div class="datatype"></div>') `

### Version :
1.4.44

**Comment by paulwarren-wk** [comment]
This is a bug - we aim to maintain XHTML validity in the viewer.
